<?php
/**
 * Declare what blocks are provided by this module.
 * Implements hook_block_info().
 */
function custom_blocks_block_info(){
    $block['welcome_message'] = array(
        'info' => t('Welcome message'),
        'cache' => DRUPAL_NO_CACHE,
    );
	
	
	
	 $block['copyright'] = array(
        'info' => t('Copyright'),
        'cache' => DRUPAL_NO_CACHE,
    );
	
	
    return $block;
}

/**
 * Define what our block is going to look like.
 * Implements hook_block_view().
 */
function custom_blocks_block_view($block_key){
    $block = array();

    if($block_key == 'welcome_message'){ //We only want to define the content of OUR block
        //This is the title of the block.
        $block['subject'] = t('');

        //Define the block content.
        $block['content'] = '<p>Hello, Welcome to my Blog!</p>';
    }
	
	
	elseif ($block_key == 'copyright'){ //We only want to define the content of OUR block
        //This is the title of the block.
        $block['subject'] = t('');

        //Define the block content.
        $block['content'] = '<p>Developed by <a href="http://gs-internet.com/" target="_blank">Gs-Internet</a> &amp; Designed by <a href="http://fikristudio.com/" target="_blank">Fikri Studio</a></p>';
    }
	
	
	

	

    return $block;
}